sudo: false
language: ruby
rvm:
  - 2.4.1
services:
  - docker
before_install:
  - gem install bundler -v 1.15.2
  - docker-compose build
  - docker-compose up -d && docker ps
before_script:
  - sleep 15  # wait for PostgreSQl to start
script:
  - docker-compose run --rm web rake db:create
  - docker-compose run --rm web rake db:migrate
  - docker-compose run --rm web rspec
after_script:
  - docker-compose down
addons:
  code_climate:
    repo_token: efde411d2e876ce4fd45042d8e90da55007e1d392b5fcc99d674466130002e3f
after_success:
  - bundle exec codeclimate-test-reporter