sudo: false
language: ruby
rvm:
  - 2.4.1
services:
  - docker
before_install:
  - gem install bundler -v 1.15.2
  - docker-compose build
  - docker-compose up -d && docker ps
script:
  - docker-compose run --rm web rake db:create
  - docker-compose run --rm web rake db:migrate
  - docker-compose run --rm web rspec 
after_success:
  - docker-compose run --rm -e CODECLIMATE_REPO_TOKEN='efde411d2e876ce4fd45042d8e90da55007e1d392b5fcc99d674466130002e3f' web codeclimate-test-reporter
  - docker-compose down