DuplicateMethodCall:
  exclude: ["AuthConcerns"]
FeatureEnvy:
  enabled: false
InstanceVariableAssumption:
  enabled: false
IrresponsibleModule:
  enabled: false
UncommunicativeVariableName:
  enabled: false
UtilityFunction:
  enabled: false
exclude_paths:
  - db
