AllCops:
  Exclude:
    - 'db/*.rb'
    - 'db/*/*.rb'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'
    - 'lint'
    - 'Gemfile'

EmptyLinesAroundModuleBody:
  Enabled: false

EmptyLinesAroundClassBody:
  Enabled: false

LineLength:
  Max: 110
  Exclude:
    - 'spec/*/*.rb'

MethodLength:
  Max: 10

BlockLength:
  Max: 5
  Exclude:
    - 'spec/*/*.rb'
    - 'bin/*'
    - 'config/routes.rb'
    - 'config/*/*.rb'

ClassAndModuleChildren:
  Enabled: false
